## Numpy 
A popular python library that deals with numbers

## Array
A collection of items of the same type. 
It is different from list! (Lists store different data types).

In this lesson we learn how to create arrays, sort them, reshape and adjust theire values.
We will also see how arrays are better than list especially when it comes to numbers.

In [4]:
# install numpy
!pip install numpy

In [1]:
# import numpy
import numpy as np

In [7]:
# generate an N-Dimensional array
my_array = np.arange(8)
print(my_array)

[0 1 2 3 4 5 6 7]


In [8]:
# check the datatype
type(my_array)

numpy.ndarray

<p>The number 8 in the above example represents a stop value;</p>
<p><em>np.arange(stop)</em></p>
<p><em>first item: 0</em></p>
<p><em>last item: stop-1</em></p>
<p>By default we always start counting from 0, if we don't want to count from 0 then we specify the first item as below </p>

In [9]:
my_array2 = np.arange(1,8)

In [10]:
print(my_array2)

[1 2 3 4 5 6 7]


In [13]:
# count with steps
my_array3 = np.arange(1, 8, 2)
print(my_array3)

[1 3 5 7]


In [14]:
# we can also work with floating point numbers
my_array3 = np.arange(1, 8, 0.5)
print(my_array3)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5]


In [15]:
# negative digits
my_array3 = np.arange(-1, 8, 0.5)
print(my_array3)

[-1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5
  6.   6.5  7.   7.5]


In [16]:
# array from lists
from_list = np.array([1,2,3])
print(from_list)


[1 2 3]


The reason we store in array instead of list is memory efficiency

In [18]:
print(type(from_list[0]))

<class 'numpy.int32'>


In [19]:
# statically set data type
from_list = np.array([1,2,3], dtype=np.int8)
print(type(from_list[0]))

<class 'numpy.int8'>


## 2D Arrays
Data with rows and columns

In [21]:
# 2D Arrays
# array from lists
from_list = np.array([[1,2,3], [4,5,6]])
print(from_list)

[[1 2 3]
 [4 5 6]]


In [27]:
# using the arange method
array_2d = np.array((np.arange(0,8,2), np.arange(1,8,2)))
print(array_2d)

[[0 2 4 6]
 [1 3 5 7]]


In [28]:
# check the type of n-dimensional array
print(array_2d.shape)

(2, 4)


In [29]:
print("1D shape: ", my_array.shape)
print("2D shape:", array_2d.shape)

1D shape:  (8,)
2D shape: (2, 4)


## Reshape
The reshape funciton allows us to flip between the number of rows and number of columns. It is not limited to the same dimensions.

In [30]:
array_2d = array_2d.reshape(4, 2)
print(array_2d)

[[0 2]
 [4 6]
 [1 3]
 [5 7]]


In [31]:
# reshape to 1-dimensional shape
array_2d = array_2d.reshape(8)
print(array_2d)

[0 2 4 6 1 3 5 7]


## Empty Arrays
sometimes we are not sure which data to store in the array so we start with an empty array.

In [35]:
# empty arrays
empty_array = np.zeros((2,2))


In [37]:
empty_array = np.ones((2,2))

In [42]:
# empty returns random values
empty_array = np.empty((2,2))

In [43]:
print(empty_array)

[[1. 1.]
 [1. 1.]]


In [44]:
# other types of array
eye_array = np.eye(3)

In [46]:
eye_array = np.eye(3, k=1)

In [48]:
eye_array = np.eye(3, k=-1)

In [49]:
print(eye_array)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [50]:
# filter 
eye_array[eye_array == 0] = 2

In [51]:
print(eye_array)

[[2. 2. 2.]
 [1. 2. 2.]
 [2. 1. 2.]]


In [52]:
# using other operators
eye_array[eye_array < 2] = 9

In [53]:
print(eye_array)

[[2. 2. 2.]
 [9. 2. 2.]
 [2. 9. 2.]]


In [54]:
# filter specific rows
eye_array[0] = 3

In [55]:
print(eye_array)

[[3. 3. 3.]
 [9. 2. 2.]
 [2. 9. 2.]]


In [57]:
# select the first two rows
eye_array[:2] = 4

In [58]:
print(eye_array)

[[4. 4. 4.]
 [4. 4. 4.]
 [2. 9. 2.]]


In [65]:
# select the last two rows
eye_array[:1] = 4

In [66]:
print(eye_array)

[[4. 4. 4.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [70]:
# Selecting columns
eye_array[:, -1] = 6

In [71]:
print(eye_array)

[[6. 4. 6.]
 [6. 5. 6.]
 [6. 5. 6.]]


## Sorting arrays
sorting organizes each row in a sequence from smallest to largest.

In [76]:
# sort arrays
sorted_array = np.sort(eye_array)

print(eye_array, '\n')
print(sorted_array)

[[6. 4. 6.]
 [6. 5. 6.]
 [6. 5. 6.]] 

[[4. 6. 6.]
 [5. 6. 6.]
 [5. 6. 6.]]


In [77]:
# sorting by columns (default axis is -1 for rows)
sorted_array = np.sort(eye_array, axis=0)
print(sorted_array)

[[6. 4. 6.]
 [6. 5. 6.]
 [6. 5. 6.]]


## copy of arrays

In [78]:
# view method
my_view = sorted_array.view()
my_copy = sorted_array.copy()

In [79]:
# view affects the original array but copy doesn't
my_view[:] = 4
print(my_view, "\n")
print(sorted_array, "\n")

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]] 

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]] 



the view method not only modifies the copied array but it also modiefies the original array.

In [80]:
my_copy[:]  = 2
print(my_copy, "\n")
print(sorted_array)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]] 

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
