## Numpy Operations

In [3]:
import numpy as np


In [6]:
#Create an empty array
arr1 = np.zeros((3,3))
arr1[:] = 2

In [7]:
print(arr1)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [10]:
arr2 = np.arange(1,10).reshape((3,3))

In [11]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
# check datypes of arrays
print(type(arr1))
print(arr1.dtype)
print(type(arr2))
print(arr2.dtype)

<class 'numpy.ndarray'>
int32
<class 'numpy.ndarray'>
int32


In [15]:
#convert arr1 to int
arr1 = np.zeros((3,3), dtype=np.int32)

# Fill method

In [18]:
arr1.fill(8)
print(arr1)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [19]:
# asign method
arr1 += 1
print(arr1)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [ ]:
Note: Numpy is written in C.

In [22]:
# arr1 /= 2

## Arithmetic methods

In [23]:
# sum of the entire arrays
array_sum = arr1.sum()
print(array_sum)

81


In [24]:
# we can also calculate each of the rows and columns separately
# calculate sum of columns by specifying the axis 0
array_sum = arr1.sum(0)
print(array_sum)

[27 27 27]


In [30]:
# we can better see it with arr2
array_sum = arr2.sum(0)
print("Array:\n", arr2, "\n")
print("Sum of array columns:", array_sum)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Sum of array columns: [12 15 18]


In [31]:
# Calculate the sum of rows by specifying the axis 1
array_sum = arr2.sum(1)
print("Array:\n", arr2, "\n")
print("Sum of array Rows:", array_sum)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Sum of array Rows: [ 6 15 24]


In [32]:
# the axis can also be written as 
array_sum = arr1.sum(axis=1)
print(array_sum)

[27 27 27]


## Product
product of the array is multiplying all the items by one another

In [37]:
array_product = arr2.prod()
print(array_product)

362880


In [42]:
# average of the array
array_average = arr2.mean()
print("Averae of the array: ", array_average)

Averae of the array:  5.0


In [44]:
# minimum and maximun values of an array
array_max, array_min = b.max(), b.min()
print("Maximun array value: ", array_max,"\nMinimum array value: ", array_min)

Maximun array value:  9 
Minimum array value:  1


In [45]:
# in some cases we want to get the index of the minimun and maximum values
array_max_idx, array_min_idx = b.argmax(), b.argmin()
print("Array index with maximum value: ", array_max,"\nArray index with minimum value: ", array_min)

Array index with maximum value:  9 
Array index with minimum value:  1


In [46]:
# the maximun index - minum index is represented by
peak_to_peak = b.ptp()
print(peak_to_peak)

8


## Faltten arrays
Instead of having it in rows and columns, we want to have a linear data.

In [53]:
# using reshape method
array_flat = arr2.reshape(arr2.size)
print(arr2, "\n")
print(array_flat)


[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3 4 5 6 7 8 9]


In [55]:
# we can also use the flatten() method, for which we don't need to pass anything
array_flat = arr2.flatten()
print(array_flat)

[1 2 3 4 5 6 7 8 9]


In [56]:
# there is also the ravel() method
array_flat = arr2.ravel()
print(array_flat)

[1 2 3 4 5 6 7 8 9]


The <code>flatten()</code> method creates a copy of the original array while the <code>rave()</code> method creates a view of the original array. The view applies changes on the original array.

## Repeat

In [57]:
# repeat vlues/arrays
array_repeat = np.repeat(255, 3)
print(array_repeat)

[255 255 255]


In [59]:
# we can use the repeat method to repeat entire arrays
array_repeat = np.repeat(arr2, 3)
print(array_repeat)

[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6 7 7 7 8 8 8 9 9 9]


In [60]:
# we can use axis to specify, if want to store in same rows
array_repeat = np.repeat(arr2, 3, axis=1)
print(array_repeat)

[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]
 [7 7 7 8 8 8 9 9 9]]


In [61]:
# or same columns
array_repeat = np.repeat(arr2, 3, axis=0)
print(array_repeat)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]
 [7 8 9]
 [7 8 9]
 [7 8 9]]


In [62]:
# to make the exact opposite
array_unique = np.unique(array_repeat, axis=0)
print(array_unique)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [63]:
# To fetch the diagonal of an array
array_diag = np.diagonal(arr2)
print(array_diag)

[1 5 9]


## Conversion and Storage

In [65]:
# conver array into lists
my_list = arr2.tolist()
print(type(my_list))
print(my_list)

<class 'list'>
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
#store array into a file
arr2.tofile("my_array.txt", sep=",")
# sep stands for seperator

arr2.