In [169]:
# import numpy (numeric python) module
import numpy as np

In [173]:
# create matrices a and b
a = np.array([[2,2,2],[2,2,2],[2,2,2]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])


## Simple Matrix Operations

In [174]:
# operations on 2 matrices
simple_ops = a + b
print(simple_ops)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [175]:
# we can also multiply, subtract and divide

simple_ops = (a + b - 2*a)/4
print(simple_ops)

[[-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]]


All basic arithmetic operations are applicable on python as well

In [176]:
# modulo operation
mudolo = b % a
print(mudolo)

[[1 0 1]
 [0 1 0]
 [1 0 1]]


In [177]:
# floor_division
floor_division = b // a
print(b/a, "\n")
print(floor_division)

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]] 

[[0 1 1]
 [2 2 3]
 [3 4 4]]


In [180]:
# we can also do the floor division using np method
floor_division = np.floor(b/a)
print(floor_division)

[[0. 1. 1.]
 [2. 2. 3.]
 [3. 4. 4.]]


## Matrix Multiplication

In [185]:
3 multiplication of the matrix elements
print(a, '\n')
print(b, '\n')
print(a*b)

[[2 2 2]
 [2 2 2]
 [2 2 2]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [186]:
# multiplication of the matrices
matrix_multiply = np.matmul(a, b)
print(matrix_multiply)

[[24 30 36]
 [24 30 36]
 [24 30 36]]


In [187]:
# we can also use the dot method
matrix_multiply = a.dot(b)
print(matrix_multiply)

[[24 30 36]
 [24 30 36]
 [24 30 36]]


In [188]:
# another way is using the @
print(a@b)

[[24 30 36]
 [24 30 36]
 [24 30 36]]
