## Numpy
Numpy is a short fo number python. It is a popular python library that deals with numbers.

## Array
Arrays are collection of items of the same data type.  It is different from lists (lists store different data types).

In [77]:

 # install numpy
#!pip install numpy



In [82]:
# import numpy
import numpy as np

In [85]:
# generate an n-deminesional array
my_array = np.arange(8)

In [86]:
print(my_array)

[0 1 2 3 4 5 6 7]


In [87]:

print("last value in the array is", my_array[-1])

last value in the array is 7


In [91]:
# we can specify the first item in the array
my_array = np.arange(2,8)
print(my_array)

[2 3 4 5 6 7]


In [95]:
# we can count in steps
my_array = np.arange(1,8,2)
print(my_array)

[1 3 5 7]


In [96]:
# floating points
my_array = np.arange(2,10,0.5)
print(my_array)

[2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [98]:
# negative digits
my_array = np.arange(-5,8,3)
print(my_array)

[-5 -2  1  4  7]


In [99]:
# check the array data type
print(type(my_array))


<class 'numpy.ndarray'>


## Creating arrays from lists

In [107]:
square_list  = [4,9,16,25]
#convert list to array
square_array = np.array(square_list)

In [108]:
print(square_list)
print(square_array)

[4, 9, 16, 25]
[ 4  9 16 25]


In [109]:
print(type(square_array[0]))

<class 'numpy.int32'>


In [113]:
# statically setting data type
square_array = np.array(square_list, dtype=np.int8)

In [114]:
print(type(square_array[0]))

<class 'numpy.int8'>


In [116]:
from_list = np.array([3,4,5])
print(from_list)

[3 4 5]


## 2D Arrays
Data with rows and columns


In [117]:
# Create 2D array from a list
from_list = np.array([[1,2,3],[4,5,6]])
print(from_list)

[[1 2 3]
 [4 5 6]]


In [127]:
# using the numpy arange method
array_2d = np.array((np.arange(0,8,2), np.arange(1,8,2)))
print(array_2d)

[[0 2 4 6]
 [1 3 5 7]]


In [128]:
# check the type of n-demensional array
print(array_2d.shape)

(2, 4)


In [121]:
print(my_array.shape)

(5,)


## Reshape
The reshape function allows us to flip between the number of rows and the number of columns.  It is not limited to the same dimensions.

In [132]:
# reshape 2D-array
array_2d = array_2d.reshape(4,2)
print(array_2d)

[[0 2]
 [4 6]
 [1 3]
 [5 7]]


In [130]:
# reshape 2d to 3D array
array_2d = array_2d.reshape(2,2,2)
# print reshaped array
print(array_2d)

[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]


In [131]:
print(array_2d.shape)

(2, 2, 2)


In [136]:
# reshare 1D array
array_2d = array_2d.reshape(8)
print(array_2d)

[0 2 4 6 1 3 5 7]


## Empty Arrays
Sometimes we are not sure which data to store in the array, we can start with an empty array.

In [142]:
# empty arrays
empty_arrays = np.zeros((4,4))

In [140]:
print(empty_arrays)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [145]:
empty_array = np.ones((4,4))
print(empty_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [155]:
# using empty
empty_array = np.empty((4,4))
print(empty_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [158]:
# other types of array
eye_array = np.eye(3)
print(eye_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [163]:
eye_array = np.eye(3, k=1)
print(eye_array)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [164]:
# filter
eye_array[eye_array == 0] = 3
print(eye_array)

[[3. 1. 3.]
 [3. 3. 1.]
 [3. 3. 3.]]


In [168]:
simple = np.eye(4, k=4)
simple[simple == 0] = 4
simple[3,3] = 1
print(simple)

[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 1.]]
